# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
#     - name: Run script file
#       run: |
#          pwd
#          ls -la src/test/java/apiTests/resources
#       shell: bash
    - name: Build with Maven
      run: mvn package -B --file pom.xml
#       run: mvn clean test
    - name: Create Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
#       id: allure-report
      with:
        allure_results: allure-results
#         gh_pages: gh-pages
#         allure_report: allure-report
        allure_history: results
    - name: Upload Allure History to Github
      if: always()
      run: |
         pwd
         ls -la
         git config user.email "islamismail3@gmail.com"
         git config user.name "islam293"
         git add results
         git commit -m "adding allure history"
         git push -u origin main
      shell: bash
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: results
        
    - name: Upload results to Calliope
      if: always()
      run: curl -X POST
           -H "x-api-key:${{ secrets.CALLIOPE_API_KEY }}"
           -H "multipart/form-data"
           -F "file=@target/surefire-reports/TEST-TestSuite.xml"
           "https://app.calliope.pro/api/v2/profile/${{ secrets.CALLIOPE_PROFILE_ID }}/import/cucumber"

